### ISSUE TITLE
Please update "Procedure to invite users to access services and resources"

### ISSUE THREAD

**Issue by e35634** [ibm-cloud-docs/vmwaresolutions#965]
Please update the content of URL below as it is outdated information(especially ④).
https://cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-iamuserinvite&locale=en#iamuserinvite-

**Comment by pokeyjo** [comment]
I recommend deleting this section and instead direct to the topic under IBM Cloud IAM -- https://cloud.ibm.com/docs/account?topic=account-iamuserinv
No reason to maintain this in multiple places since there is no way to automatically pull changes into the IC4V docs.

Please refer to @smoonen for final determination. (jmbrown@us.ibm.com)

**Comment by smoonen** [comment]
I agree; I think we can link to this as a new first procedure under [Managing user accounts and settings](https://cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-useraccount).

**Comment by ClaireZheng** [comment]
@smoonen @pokeyjo @delia-rusu 
I have inserted the "invite users" content to [Managing user accounts and settings](https://test.cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-useraccount), please have a look and let me know whether OK. The detailed doc updates are being tracked in ID issue https://github.ibm.com/tornado/tracker/issues/26840.

**Comment by ClaireZheng** [comment]
@pokeyjo @smoonen 
Doc updates have been completed. The changes will be pushed to production along with our GA on January.
